### ISSUE TITLE
[기능] Vue Migration

### ISSUE THREAD

**Issue by Jomalang** [Jomalang/ggogit#119]
담당자: 조현진, 장재영, 주진필, 한태규, 이희권
작업 내용: fragments파일 내 HTML을 `.vue` 컴포넌트 파일로 마이그레이션
관련 이슈: #114, #117 
작업 시작 일자: 2024-10-08

작업 상세 내욜

- [x] #120
- [x] #124
- [x] #125
- [x] #121
- [x] #126

작업 완료 예상 일자: 2024-10-12

**Comment by TaegyuHan** [comment]
### svg 파일은 path: `/public/src` 경로에서 관리하고 있습니다.
![image](https://github.com/user-attachments/assets/3fbb1eff-38db-422e-8477-05b368533918)

css url 속성에서 직접적으로 svg 파일을 사용할 일이 있어서 추가 하였습니다.
![image](https://github.com/user-attachments/assets/8bbf8dce-0e54-4d3a-a441-9ecb8da0824e)
