### ISSUE TITLE
희권 - tab-comment, bar, bot-bar

### ISSUE THREAD

**Issue by TaegyuHan** [Jomalang/ggogit#125]
담당자: 이희권
작업 내용: tab-comment, bar, bot-bar 프래그먼트 > Vue 컴포넌트 작업 완료
관련 이슈: https://github.com/Jomalang/ggogit/issues/119
작업 시작 일자: 2024-10-09

작업 상세 내용

- [x] tab-comment.html 프래그먼트 Vue컴포넌트화
- [x] bar.html 프래그먼트 Vue컴포넌트화
- [x] bot-bar.html 프래그먼트 Vue컴포넌트화

테스트 상세 내용
- 브라우저 화면에서 UI 도작 확인
- 
작업 완료 예상 일자: 2024-10-09
작업 완료 일자: 2024-10-09

이전 작업 이슈: https://github.com/Jomalang/ggogit/issues/114

**Comment by Gun-code** [comment]
fragment 중 tab-comment(댓글 탭)의 TabComment의 경우 다른 fragment를 가져와서 출력하는 것 외엔 별도의 기능이 없어 해당 fragment 사용 시 component를 별도로 가져다 쓰는 방향으로 작업 부탁드립니다~
